CREATE TABLE ACCIDENTS (
    id bigserial PRIMARY KEY,
    dataset_id bigint NOT NULL,
    accident_hour int default 0,
    day_of_week int NOT NULL,
    driver_age_group int NOT NULL,
    driver_gender int NOT NULL,
    driver_experience int NOT NULL,
    vehicle_type int NOT NULL,
    vehicle_defected boolean default false,
    road_alignment int NOT NULL,
    road_surface_type int NOT NULL,
    road_surface_condition int NOT NULL,
    light_condition int NOT NULL,
    weather_condition int NOT NULL,
    vehicle_movement int NOT NULL,
    collision_type int NOT NULL,
    collision_cause int NOT NULL,
    vehicles_number int NOT NULL check (vehicles_number between 1 and 10),
    casualties_number int NOT NULL check (casualties_number between 0 and 10),
    accident_severity int NOT NULL,
    accidents_number int NOT NULL check (accidents_number between 1 and 50),
    FOREIGN KEY(dataset_id) REFERENCES datasets(id)
);